### ISSUE TITLE
Sudden Error in client window after short time

### ISSUE THREAD

**Issue by LupoLucario** [mrexodia/BoomPowGui#1]
All is working fine, but every time after 10-15 minutes of working, an error occurs in the client window.
It seems to work fine though even after the error occurs. But when it does, clicking on Stop button results in freezing. The program can only be terminated by task manager then.

The error message spams the console until hitting the Stop button. Here is (I hope) one complete error message:

```
Task exception was never retrieved
future: <Task finished name='Task-1253' coro=<WorkHandler.process_queue_item() done, defined at C:\BoomPowGui_v3\work_handler.py:122> exception=TimeoutError()>
Traceback (most recent call last):
  File "C:\BoomPowGui_v3\work_handler.py", line 124, in process_queue_item
    res = await self.session.post(self.worker_uri, json={
  File "C:\BoomPowGui_v3\python-3.8.3-embed-amd64\lib\site-packages\aiohttp\client.py", line 544, in _request
    await resp.start(conn)
  File "C:\BoomPowGui_v3\python-3.8.3-embed-amd64\lib\site-packages\aiohttp\client_reqrep.py", line 905, in start
    self._continue = None
  File "C:\BoomPowGui_v3\python-3.8.3-embed-amd64\lib\site-packages\aiohttp\helpers.py", line 656, in __exit__
    raise asyncio.TimeoutError from None
asyncio.exceptions.TimeoutError
```

I tried several things: other network (wired and wireless), other user account, even other system. But no change at all.

My system:
Win10 64 Bit
Intel i5
8GB of RAM

**Comment by mrexodia** [comment]
The gui is just wrapping https://github.com/BananoCoin/boompow

You can try updating the scripts to the latest version (just replace all the .py files) and if that doesn’t work open an issue in that repository.

**Comment by LupoLucario** [comment]
Thanks for the answer.
I replaced all of the .py files but there is no change.
I think it has something to do with the .py files in the embedded version of python.
The boompow repository is working fine without the GUI.
